# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: گیت ویرایش دوم
author: حمزه جوادی
email: javadi@daloo.ir
motto: برگردان فارسی کتاب پروگیت ویرایش دوم
baseurl: "" # the subpath of your site, e.g. /blog
url: "progit2-fa.ir" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  hjavadish

keywords: کامپیوتر برنامه‌نویسی وب
copyright: "Commons Attribution 4.0 International"
robot: 
description: > # this means to ignore newlines
  سکوی انتشار مطالبی در مورد دانش تولید نرم‌افزار و ایده‌ها و علایق شخصی‌ام.
long_description: >
  بچه که بودیم همیشه برای بازی خونه می‌ساختیم. حالا هم نمونه‌اش رو در وب ساختم.
  اینجا سکوی انتشار مطالبی در مورد دانش تولید نرم‌افزار و ایده‌ها و علایق شخصی‌ام است،
  بویژه راه‌حل‌های مهندسی که باعث رشد و پیشرفتم شده است و می‌تواند مورد استفاده دیگران هم قرار بگیرد.
favicon: assets/img/favicon.png
permalink: :title.html
timezone: Europe/Berlin

paginate: 3
paginate_path: /page:num/

tag_page_layout: tag_page
tag_page_dir: tag

collections:
  projects:
    output: true

comment_system: static # or disqus. Default is no comments.
#disqus_shortname: 
#google_analytics_id: UA-57282325-1
feedburner_id: REPLACE_WITH_YOUR_FEEDBURNER_ID

lang: fa_IR
github:
  username: hjavadish
  repository: progit2-fa.github.io
# Footer logo will disappear if not set.
#logo: assets/img/me.png

exclude:
- scripts
- cache
- .bundle
- .sass-cache
- reply-mail-hook
- vendor
- CONTRIBUTING.md
- netlify.toml
- wercker.yml
- LICENSE
- env.sh
- screenshot.png
- jekyll-theme-mehdix-rtl.sublime-project
- jekyll-theme-mehdix-rtl.sublime-workspace
- travis.yml
- jekyll-theme-mehdix-rtl.gemspec
- rebuild_comments.py
- README.md
- Gemfile
- Gemfile.lock
















# Build settings
markdown: kramdown
theme: jekyll-theme-mehdix-rtl
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
# theme: jekyll-theme-mehdix-rtl
